# Generated by Django 4.0 on 2021-12-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('lib_id', models.AutoField(primary_key=True, serialize=False, verbose_name='lib_id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='book_id')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('pub_year', models.IntegerField(verbose_name='Publish year')),
                ('lib_id', models.ForeignKey(db_column='lib_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.library')),
            ],
        ),
    ]
